project_id = "toxadhuqzdydliplhrws"

[functions.twilio-inbound]
verify_jwt = false

[functions.send-daily-prompts]
verify_jwt = false

[functions.phone-change-initiate]
verify_jwt = true

[functions.phone-change-confirm]
verify_jwt = true

[functions.create-missing-user]
verify_jwt = false