// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://toxadhuqzdydliplhrws.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRveGFkaHVxemR5ZGxpcGxocndzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMzQwNTEsImV4cCI6MjA2OTgxMDA1MX0.H1gz-EHYWU2PJQV6zLMZKveUgWFnCmkvnNbCPm-25FY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});