name: Weekly Journal Blast

on:
  schedule:
    # Every Sunday at 7 PM PST (Monday 2 AM UTC during PST, 3 AM UTC during PDT)
    - cron: '0 2 * * 1'  # UTC time for PST
  workflow_dispatch:  # Allow manual triggering for testing
    inputs:
      dryRun:
        description: 'Run in dry-run mode (no emails sent)'
        required: false
        default: 'true'
        type: boolean
      testTo:
        description: 'Override recipient email for testing'
        required: false
        type: string
      limit:
        description: 'Limit number of users to process'
        required: false
        default: '10'
        type: string

jobs:
  send-weekly-journals:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Send Weekly Journal Blast
        env:
          WEEKLY_BLAST_DEFAULT_DRY_RUN: 'true'
        run: |
          # Set parameters from inputs or defaults
          DRY_RUN="${{ github.event.inputs.dryRun || 'true' }}"
          TEST_TO="${{ github.event.inputs.testTo }}"
          LIMIT="${{ github.event.inputs.limit || '10' }}"
          
          echo "Triggering weekly journal blast..."
          echo "Parameters: dryRun=${DRY_RUN}, testTo=${TEST_TO}, limit=${LIMIT}"
          
          # Build request body
          REQUEST_BODY="{\"dryRun\": ${DRY_RUN}"
          if [ -n "${TEST_TO}" ]; then
            REQUEST_BODY="${REQUEST_BODY}, \"testTo\": \"${TEST_TO}\""
          fi
          if [ -n "${LIMIT}" ]; then
            REQUEST_BODY="${REQUEST_BODY}, \"limit\": ${LIMIT}"
          fi
          REQUEST_BODY="${REQUEST_BODY}}"
          
          echo "Request body: ${REQUEST_BODY}"
          
          response=$(curl -s -o /tmp/response.json -w "%{http_code}" \
            -X POST \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
            -H "Content-Type: application/json" \
            "${{ secrets.SUPABASE_URL }}/functions/v1/weekly-journal-blast" \
            -d "${REQUEST_BODY}")
          
          echo "HTTP Status: $response"
          
          if [ "$response" -eq 200 ]; then
            echo "✅ Weekly journal blast completed successfully"
            echo "Response:"
            cat /tmp/response.json | jq .
          else
            echo "❌ Weekly journal blast failed with status $response"
            echo "Response:"
            cat /tmp/response.json
            exit 1
          fi

      - name: Upload Response Log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: weekly-blast-response-${{ github.run_number }}
          path: /tmp/response.json
          retention-days: 30